### ISSUE TITLE
Aggiornare i codici nell'auditMessagge nell'OpenAPI "catalogo-ssu_to_bo.yaml"

### ISSUE THREAD

**Issue by Liaron** [AgID/specifiche-tecniche-DPR160-2010#33]
From: AgID

Aggiornare i codici, secondo i codici del ET, nel pattern degli auditMessage nell'OpenAPI "catalogo-ssu_to_bo.yaml"

**Comment by vintra73** [comment]
propose solution into https://github.com/AgID/specifiche-tecniche-DPR160-2010/pull/43
