### ISSUE TITLE
open API cataloto_to_fo "repo privato issue #2)

### ISSUE THREAD

**Issue by Liaron** [AgID/specifiche-tecniche-DPR160-2010#34]
From: Infocamere

necessario aggiungere path /instance_descriptor/{cui_uuid} per permettere al front-office di recuperare il descrittore nelle fasi di correzione, integrazione e conclusione di un processo SUAP

aggiungere all'API esposte verso il frontoffice l'API /instance_descriptor/{cui_uuid}

**Comment by vintra73** [comment]
propose solution into https://github.com/AgID/specifiche-tecniche-DPR160-2010/pull/43
