### ISSUE TITLE
Normalizzazione property lifeevent schema #/components/schemas/GenericEntity

### ISSUE THREAD

**Issue by Liaron** [AgID/specifiche-tecniche-DPR160-2010#35]
From: Infocamere

La property lifeevent è definita in modo ambiguo nello schema
Proceeding: description: procedimento amministrativo allOf: - {$ref: '#/components/schemas/GenericEntity'} type: object required: [typology, **life_event**, territorial_scope] properties: typology: {title: tipologia del procedimento, type: string} **lifeevent**: {title: evento della vita dell'attività afferente al procedimento, type: string} territorial_scope: {title: ambito territoriale del procedimento (codice istat a 8 cifre e 00000000 per Nazionale), type: string} example: {id: 1, version: 1.0.0, description: Entita  procedimento, typology: esercizio_vicinato, lifeevent: apertura, territorial_scope: 0}

Nei require c'è life_event come properties è descritta come lifeevent

**Comment by vintra73** [comment]
propose solution into https://github.com/AgID/specifiche-tecniche-DPR160-2010/pull/43
