### ISSUE TITLE
[ComUnica to FrontOffice SUAP] enum operation retry

### ISSUE THREAD

**Issue by Liaron** [AgID/specifiche-tecniche-DPR160-2010#42]
From: Infocamere

L'attuale enum_operation della retry è esposta da comunica verso il FO è [ send_instance, cancel_instance ] dovrebbe essere [ notify_receipt, cancel_instance ]

**Comment by vintra73** [comment]
propose solution into https://github.com/AgID/specifiche-tecniche-DPR160-2010/pull/43
