### ISSUE TITLE
Titolo

### ISSUE THREAD

**Issue by FCiminelliACN** [AgID/specifiche-tecniche-DPR160-2010#44]
Descrizione

https://github.com/AgID/specifiche-tecniche-DPR160-2010/blob/19e2bccd8eda0acf05f49a8ad4a0460359b4f322/openAPI/fo_to_bo.yaml#L40

**Comment by vintra73** [comment]
issues create per demo delle regole utilizzate dal gruppo tecnico per l'utilizzo di github nella gestione dei round di aggiornamento delle specifiche tecniche

**Comment by vintra73** [comment]
issues create per demo delle regole utilizzate dal gruppo tecnico per l'utilizzo di github nella gestione dei round di aggiornamento delle specifiche tecniche
