### ISSUE TITLE
recupero  componente informatica per data

### ISSUE THREAD

**Issue by nirubino** [AgID/specifiche-tecniche-DPR160-2010#45]
Al fine di permettere il recupero di una componente informatica utilizzata in un periodo precedente a quello attuale, si ritiene necessario prevedere un API che permetta di ottenere la componente informatica attiva ad una data specifica.

Questa API permetterebbe di gestire gli eventuali cambi di piattaforma attuati dai SUAP/entiterzi, in questo caso infatti le pratiche precedenti allo switch possono continuare ad essere lavorate sulle componenti iniziali, permettendo agli altri attori di individuare le coordinate della componente utilizzando le date presenti nell'istanza dell'instance descdriptor

**Comment by franthemanIT** [comment]
Se posso, parallelamente sarebbe da gestire la cessazione di una piattaforma.
Non si puo' dare per scontato che si mantenga operativa una piattaforma dismessa "per lo storico".

**Comment by vintra73** [comment]
@franthemanIT la rimando a https://github.com/AgID/specifiche-tecniche-DPR160-2010/issues/46#issuecomment-1912125523

grazie

**Comment by vintra73** [comment]
nell'incontro dell'8/2 del GT sono state ipotizzate due scenari risolutivi:
1. aggiornare gli artefatti delle specifiche, di specie OpenAPI, a valle della valutazione dell'impatto sulla governance e scalabilità dell'ecositema SSU
2. non aggiornare gli artefatti delle specifiche tecniche in quanto lo swicht tra sistemi diversi dello stesso Ente può essere gestito all'interno del dominio dello stesso prevedendo un dispatcher interno che, utilizzando del riferimento del CUI, instrada al sistema che sta gestendendo la singola istanza

**Comment by LeonardoBorselli** [comment]
LA modifica

**Comment by LeonardoBorselli** [comment]
L’esigenza di evoluzione dei sistemi è ovviamente da prevedere in quanto per modifiche connesse a contratti, funzionalità, sicurezza, organizzazione interna può accadere ce un ente debba sostituire il proprio sistema di gestione. Le modalità di sostituzione sono varie; fra queste la possibilità di avere attivi più sistemi di Back Office è un’opzione diffusa.

Occorre comunque valutare anche la responsabilità nella comunicazioni fra soggetti. Il mittente e il destinatario delle comunicazioni (interazioni a mezzo API in questo contesto) devono avere la certezza di mutuo riconoscimento.

Attivare diversi end-point sulla base, ad esempio, di una data richiede in primis di identificare quale data debba essere la data fra quelle disponibili; ad esempio l’avvio del procedimento, la data di prima comunicazione all’ente destinatario, … Comunque occorre chiarire la responsabilità del mittente e del destinatario in caso di utilizzo di un indirizzo errato da parte del mittente.

La soluzione proposta sembra far ricadere sul mittente la responsabilità dell’utilizzo di un indirizzo di destinazione basato sulle scelte organizzative del destinatario.

Oltre a sollevare dubbi per la complessità derivanti dalla necessità di continuo aggiornamento degli indirizzi derivanti dall’elevato numero di enti coinvolti ci si pone il problema se la responsabilità sia collocata nella giusta parte, o se sarebbe più opportuno considerare responsabilità del destinatario esporre un solo end point e instradare internamente le istanze al sistema opportuno rendendo questa scelta non impattante sul mittente.

Il responsabile del procedimento SUAP ha la responsabilità di inoltrare la pratica sulla base della competenza dei procedimenti attivati dall’Impresa/Cittadino, indipendentemente dall’organizzazione interna dell’Amministrazione competente e/o dal/dai sistemi informativi esposti dall’Amministrazione. L’organizzazione e i sistemi informativi potrebbero cambiare nel tempo ma senza influenzare la responsabilità del SUAP

Il CatalogoSSU contiene i metadati per l’istanziazione dei protocolli di comunicazione, per cui la responsabilità dell’instradamento deve essere in capo al CatalogoSSU

**Comment by vintra73** [comment]
chiusura issue concordato dal tutto il Gruppo nell'incontro del 13/02/2024
