### ISSUE TITLE
Relazione fra SSU e PDND

### ISSUE THREAD

**Issue by franthemanIT** [AgID/specifiche-tecniche-DPR160-2010#46]
Leggendo le specifiche mi pare di capire che le API che le componenti informatiche del SSU devono esporre richiedono autenticazione tramite PDND (security: bearerAuth) e firma del payload (security: Agid.JWT-Signature).

Chiedo conferma:
- ogni API va esposta su PDND come erogatore?
- il fruitore deve preventivamente fare accordo di fruizione e caricare il materiale crittografico su PDND per ciascun possibile erogatore?

**Comment by vintra73** [comment]
Buongiorno @franthemanIT, 
le chiedo scusa ma il presente canale è stato costruito per permettere al gruppo tecnico di cui all'articolo 5 dell'Allegato Tecnico al DPR 160/2010 di dare seguito al maintenance delle specifiche di cui allo stesso.

Il tema da lei posto afferisce al modello organizzativo del SSU che non rientra nel perimetro delle stesse.

Grazie
